export const CREATE__CLASSIFICADOS__START = "CREATE__CLASSIFICADOS__START"
export const CREATE__CLASSIFICADOS__SUCCESS = "CREATE__CLASSIFICADOS__SUCCESS"
export const CREATE__CLASSIFICADOS__ERROR = "CREATE__CLASSIFICADOS__ERROR"
export const CREATE__CLASSIFICADOS = "CREATE__CLASSIFICADOS"


export const DELETE__CLASSIFICADOS__START = "DELETE__CLASSIFICADOS__START"
export const DELETE__CLASSIFICADOS__SUCCESS = "DELETE__CLASSIFICADOS__SUCCESS"
export const DELETE__CLASSIFICADOS__ERROR = "DELETE__CLASSIFICADOS__ERROR"

export const SUCCES__MSG__HANDLER = "SUCCES__MSG__HANDLER"
export const ERROR__MSG__HANDLER = "ERROR__MSG__HANDLER"

